BlogApp/urls.py
"""Defines URL patterns for learning_logs."""

from django.urls import path

from . import views

app_name = 'BlogApp'

urlpatterns = [

#homepage
     path('', views.index, name='index'),
     path('blog', views.blog, name='blog'),
     path('post', views.post, name='post'),
     path('search', views.search, name='search'),
     
     
]

blogingapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('BlogApp.urls')),
    path('users/', include('users.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
"""Defines URL patterns for users"""
from django.urls import path, include
from . import views

app_name = 'users'

urlpatterns = [
# Include default auth urls.
path('', include('django.contrib.auth.urls')),
path('register/', views.register, name='register'),
path('login/', views.loginpage, name='login'),

]

BlogApp/models.py
from django.db import models
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()

class Author(models.Model):
	user = models.OneToOneField(User, on_delete=models.CASCADE)
	profile_picture = models.ImageField()

	def __str__(self):
		return self.user.username

class Category(models.Model):
	title = models.CharField(max_length=20,)

	def __str__(self):
		return self.title

class Post(models.Model):
	title = models.CharField(max_length=100)
	overview = models.TextField()
	timestamp = models.DateTimeField(auto_now_add=True)
	comment_count = models.IntegerField(default = 0)
	view_count = models.IntegerField(default = 0)
	author = models.ForeignKey(Author, on_delete=models.CASCADE)
	thumbnail = models.ImageField()
	categories = models.ManyToManyField(Category)
	featured = models.BooleanField()

	def __str__(self):
		return self.title

class Signup(models.Model):
	email = models.EmailField()
	timestamp = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return self.email

users/models.py
from django.db import models

# Create your models here.

users/forms.py
from django.forms import ModelForm

from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms

class CreatUserForm(UserCreationForm):
	class Meta:
		model = User
		fields = ['username', 'email', 'password1', 'password2']
		

BlogApp/views.py
from django.db.models import Count, Q
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import render
from .models import Post, Signup


# Create your views here.
def search(request):
	queryset = Post.objects.all()
	query =  request.GET.get('q')
	if query:
		queryset = queryset.filter(
		    Q(title__icontains=query) |
		    Q(overview__icontains=query)

		).distinct()
	context ={
	'queryset':queryset
	}
	return render(request, 'BlogApp/search_result.html', context)		

def get_category_count():
	queryset = Post \
	    .objects \
	    .values('categories__title')\
	    .annotate(Count('categories__title'))
	return queryset    


def index(request):
	featured = Post.objects.filter(featured=True)
	latest = Post.objects.order_by('-timestamp')[0:3]
	if request.method == "POST":
		email = request.POST['email']
		new_signup = Signup()
		new_signup.email = email
		new_signup.save()
	context = {
	    'object_list': featured,
	    'latest': latest	 
	}
	return render(request, 'BlogApp/index.html', context)

def blog(request):
	category_count = get_category_count() 
	most_recent = Post.objects.order_by('-timestamp')[:3]
	post_list = Post.objects.all()
	paginator = Paginator(post_list, 1)
	page_request_var ='page'
	page = request.GET.get(page_request_var)
	try:
		paginated_queryset = paginator.page(page)
	except PageNotAnInteger:
		paginated_queryset = paginator.page(1)
	except EmptyPage:
		paginated_queryset = paginator.page(paginator.num_pages)
		
	context = {
	    'queryset': paginated_queryset,
	    'most_recent': most_recent,  
	    'page_request_var': page_request_var,
	    'category_count': category_count  
	}
	return render(request, 'BlogApp/blog.html', context)

def post(request):
	return render(request, 'BlogApp/post.html', {})

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from  .forms import  CreatUserForm
from django.contrib import messages

# Create your views here.


def register(request):
	if request.method != 'POST':
		form = CreatUserForm()
	else:
		form = CreatUserForm(data=request.POST)
		if form.is_valid():
			new_user = form.save()
			user = form.cleaned_data.get('username')
			messages.success(request, 'Acount was Created for' + user)

			login(request, new_user)
			return redirect('BlogApp:index')
	context = {'form': form}
	return render(request, 'registration/register.html', context)

def loginpage(request):

	if request.method == 'POST':
		username = request.POST.get('username')
		password =request.POST.get('password')

		user = authenticate(request, username=username, password=password)

		if user is not None:
			login(request, user)
			return redirect('BlogApp:index')

		context = {}
		return render(request, 'registration/login.html')

BlogApp/templates/BlogApp/base.html
{% load static %}
<!DOCTYPE html>
<html>
<body>
  <header class="header">
    <body>
      <!-- Main Navbar-->
      <nav class="navbar navbar-expand-lg">
        <div class="search-area">
          <div class="search-area-inner d-flex align-items-center justify-content-center">
            <div class="close-btn"><i class="icon-close"></i></div>
            <div class="row d-flex justify-content-center">
              <div class="col-md-8">
                <form action="#">
                  <div class="form-group">
                    <input type="search" name="search" id="search" placeholder="What are you looking for?">
                    <button type="submit" class="submit"><i class="icon-search-1"></i></button>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
        <div class="container">
          <!-- Navbar Brand -->
          <div class="navbar-header d-flex align-items-center justify-content-between">
            <!-- Navbar Brand --><a href="/" class="navbar-brand">BlogApp</a>
            <!-- Toggle Button-->
            <button type="button" data-toggle="collapse" data-target="#navbarcollapse" aria-controls="navbarcollapse" aria-expanded="false" aria-label="Toggle navigation" class="navbar-toggler"><span></span><span></span><span></span></button>
          </div>
          <!-- Navbar Menu -->
          <div id="navbarcollapse" class="collapse navbar-collapse">
            <ul class="navbar-nav ml-auto">
              <li class="nav-item"><a href="/" class="nav-link active "></a>
              </li>
              <li class="nav-item"><a href="/blog" class="nav-link "></a>
              </li>
              <li class="nav-item"><a href="/post" class="nav-link "></a>
              </li>
              <li class="nav-item"><a href="#" class="nav-link "></a>
              </li>
            </ul>
          </div>
        </div>
      </nav>
    </header>
</body>
	
	<title></title>
	<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Bootstrap Blog - B4 Template by Bootstrap Temple</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="robots" content="all,follow">
    <link rel="stylesheet" href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'vendor/font-awesome/css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static  'css/fontastic.css' %}">
    <link rel="stylesheet" href="{% static 'https://fonts.googleapis.com/css?family=Open+Sans:300,400,700' %}">
    <link rel="stylesheet" href="{% static  'vendor/@fancyapps/fancybox/jquery.fancybox.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.default.css" id="theme-stylesheet' %}">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <link rel="shortcut icon" href="{% static 'favicon.png' %}">
    <!-- Tweaks for older IEs--><!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script><![endif]-->
  </head>
     <!-- JavaScript files-->
    <script src="static/vendor/jquery/jquery.min.js"></script>
    <script src="static/vendor/popper.js/umd/popper.min.js"> </script>
    <script src="static/vendor/bootstrap/js/bootstrap.min.js"></script>
    <script src="static/vendor/jquery.cookie/jquery.cookie.js"> </script>
    <script src="static/vendor/@fancyapps/fancybox/jquery.fancybox.min.js"></script>
    <script src="static/js/front.js"></script>
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.blue.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.default.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.green.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.pink.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.red.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.sea.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.violet.css' %}">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">


	{% block content %}{% endblock content %}
</body>
</html>

BlogApp/templates/BlogApp/base2.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
<!DOCTYPE html>
<html>
<body>
  
  
    <title></title>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Bootstrap Blog - B4 Template by Bootstrap Temple</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="robots" content="all,follow">
    <link rel="stylesheet" href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'vendor/font-awesome/css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static  'css/fontastic.css' %}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,700">
    <link rel="stylesheet" href="{% static  'vendor/@fancyapps/fancybox/jquery.fancybox.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.default.css" id="theme-stylesheet' %}">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <link rel="shortcut icon" href="{% static 'favicon.png' %}">

<body>
<header class="header">
      <!-- Main Navbar-->
      <nav class="navbar navbar-expand-lg">
        <div class="search-area">
          <div class="search-area-inner d-flex align-items-center justify-content-center">
            <div class="close-btn"><i class="icon-close"></i></div>
            <div class="row d-flex justify-content-center">
              <div class="col-md-8">
                <form action="#">
                  <div class="form-group">
                    <input type="search" name="search" id="search" placeholder="What are you looking for?">
                    <button type="submit" class="submit"><i class="icon-search-1"></i></button>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
        <div class="container">
          <!-- Navbar Brand -->
          <div class="navbar-header d-flex align-items-center justify-content-between">
            <!-- Navbar Brand --><a href="/" class="navbar-brand">BlogApp</a>
            <!-- Toggle Button-->
            <button type="button" data-toggle="collapse" data-target="#navbarcollapse" aria-controls="navbarcollapse" aria-expanded="false" aria-label="Toggle navigation" class="navbar-toggler"><span></span><span></span><span></span></button>
          </div>
          <!-- Navbar Menu -->
          <div id="navbarcollapse" class="collapse navbar-collapse">
            <ul class="navbar-nav ml-auto">
              <li class="nav-item"><a href="/" class="nav-link active ">Home</a>
              </li>
              <li class="nav-item"><a href="/blog" class="nav-link ">Blog</a>
              </li>
              <li class="nav-item"><a href="/post" class="nav-link ">Post</a>
              </li>
              <li class="nav-item"><a href="#" class="nav-link ">Contact</a>
              </li>
            </ul>
            <div class="navbar-text"><a href="#" class="search-btn"><i class="icon-search-1"></i></a></div>
            <ul class="langs navbar-text"><a href="#" class="active">EN</a><span></span><a href="#">ES</a></ul>
          </div>
        </div>
      </nav>
    </header>

      <!-- JavaScript files-->
    <script src="static/vendor/jquery/jquery.min.js"></script>
    <script src="static/vendor/popper.js/umd/popper.min.js"> </script>
    <script src="static/vendor/bootstrap/js/bootstrap.min.js"></script>
    <script src="static/vendor/jquery.cookie/jquery.cookie.js"> </script>
    <script src="static/vendor/@fancyapps/fancybox/jquery.fancybox.min.js"></script>
    <script src="static/js/front.js"></script>
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.blue.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.default.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.green.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.pink.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.red.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.sea.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.violet.css' %}">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">

</body>
</html>
</head>
{% block content %}{% endblock content %}
</body>
</html>
<!-- Page Footer-->
    <footer class="main-footer">
      <div class="container">
        <div class="row">
          <div class="col-md-4">
            <div class="logo">
              <h6 class="text-white">Bootstrap Blog</h6>
            </div>
            <div class="contact-details">
              <p>53 Broadway, Broklyn, NY 11249</p>
              <p>Phone: (020) 123 456 789</p>
              <p>Email: <a href="mailto:info@company.com">Info@Company.com</a></p>
              <ul class="social-menu">
                <li class="list-inline-item"><a href="#"><i class="fa fa-facebook"></i></a></li>
                <li class="list-inline-item"><a href="#"><i class="fa fa-twitter"></i></a></li>
                <li class="list-inline-item"><a href="#"><i class="fa fa-instagram"></i></a></li>
                <li class="list-inline-item"><a href="#"><i class="fa fa-behance"></i></a></li>
                <li class="list-inline-item"><a href="#"><i class="fa fa-pinterest"></i></a></li>
              </ul>
            </div>
          </div>
          <div class="col-md-4">
            <div class="menus d-flex">
              <ul class="list-unstyled">
                <li> <a href="#">My Account</a></li>
                <li> <a href="#">Add Listing</a></li>
                <li> <a href="#">Pricing</a></li>
                <li> <a href="#">Privacy &amp; Policy</a></li>
              </ul>
              <ul class="list-unstyled">
                <li> <a href="#">Our Partners</a></li>
                <li> <a href="#">FAQ</a></li>
                <li> <a href="#">How It Works</a></li>
                <li> <a href="#">Contact</a></li>
              </ul>
            </div>
          </div>
          <div class="col-md-4">
            <div class="latest-posts"><a href="#">
                <div class="post d-flex align-items-center">
                  <div class="image"><img src="static/img/small-thumbnail-1.jpg" alt="..." class="img-fluid"></div>
                  <div class="title"><strong>Hotels for all budgets</strong><span class="date last-meta">October 26, 2016</span></div>
                </div></a><a href="#">
                <div class="post d-flex align-items-center">
                  <div class="image"><img src="static/img/small-thumbnail-2.jpg" alt="..." class="img-fluid"></div>
                  <div class="title"><strong>Great street atrs in London</strong><span class="date last-meta">October 26, 2016</span></div>
                </div></a><a href="#">
                <div class="post d-flex align-items-center">
                  <div class="image"><img src="static/img/small-thumbnail-3.jpg" alt="..." class="img-fluid"></div>
                  <div class="title"><strong>Best coffee shops in Sydney</strong><span class="date last-meta">October 26, 2016</span></div>
                </div></a></div>
          </div>
        </div>
      </div>
      <div class="copyrights">
        <div class="container">
          <div class="row">
            <div class="col-md-6">
              <p>&copy; 2017. All rights reserved. Your great site.</p>
            </div>
            <div class="col-md-6 text-right">
              <p>Template By <a href="https://bootstrapious.com/p/bootstrap-carousel" class="text-white">Bootstrapious</a>
                <!-- Please do not remove the backlink to Bootstrap Temple unless you purchase an attribution-free license @ Bootstrap Temple or support us at http://bootstrapious.com/donate. It is part of the license conditions. Thanks for understanding :)                         -->
              </p>
            </div>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>
</head>

BlogApp/templates/BlogApp/blog.html
{% extends "BlogApp/base2.html" %}
{% block content %}
     <!DOCTYPE html>
<html>
  <body>
       <div class="container">
      <div class="row">
        <!-- Latest Posts -->
        <main class="posts-listing col-lg-8"> 
          <div class="container">
            <div class="row">
              <!-- post -->
              {% for post in queryset %}
              <div class="post col-xl-6">
                <div class="post-thumbnail"><a href="{% url 'BlogApp:post' %}"><img src="{{ post.thumbnail.url }}" alt="..." class="img-fluid"></a></div>
                <div class="post-details">
                  <div class="post-meta d-flex justify-content-between">
                    <div class="date meta-last">20 May | 2016</div>
                    {% for cat in post.categories.all %}
                    <div class="category"><a href="#">{{ cat }}</a></div>
                    {% endfor %}
                  </div><a href="{% url 'BlogApp:post' %}">
                    <h3 class="h4">{{ post.title }}</h3></a>
                  <p class="text-muted">{{ post.overview }}</p>
                  <footer class="post-footer d-flex align-items-center">
                    <a href="#" class="author d-flex align-items-center flex-wrap">
                      <div class="avatar"><img src="{{ post.author.profile_picture.url  }}" alt="..." class="img-fluid"></div>
                      <div class="title"><span>{{ post.author.user.username }}</span></div>
                    </a>
                    <div class="date"><i class="icon-clock"></i>{{ post.timestamp|timesince }} ago</div>
                    <div class="comments meta-last"><i class="icon-comment"></i>{{ post.comment_count }}</div>
                  </footer>
                </div>
              </div>
              {% endfor %}
              </div>
            <!-- Pagination -->
            <nav aria-label="Page navigation example">
              <ul class="pagination pagination-template d-flex justify-content-center">
                {% if queryset.has_previous %}
                <li class="page-item"><a href="?{{page_request_var}}={{ queryset.previous_page_number }}" class="page-link"> <i class="fa fa-angle-left"></i></a></li>
                {% endif %}
                <li class="page-item"><a href="?{{page_request_var}}={{ queryset.qnumber }}" class="page-link active">{{ queryset.number }}</a></li>
                {% if queryset.has_next %}
                <li class="page-item"><a href="?{{page_request_var}}={{ queryset.next_page_number }}" class="page-link"> <i class="fa fa-angle-right"></i></a></li>
                {% endif %}
              </ul>
            </nav>
          </div>
        </main>
        <aside class="col-lg-4">
          <!-- Widget [Search Bar Widget]-->
          <div class="widget search"> 
            <header>
              <h3 class="h6">Search the blog</h3>
            </header>
            <form action="{% url 'BlogApp:search' %}" class="search-form">
              <div class="form-group">
                <input type="text"  name="q" placeholder="What are you looking for?">
                <button type="submit" class="submit"><i class="icon-search"></i></button>
              </div>
            </form>
          </div>
          <!-- Widget [Latest Posts Widget]        -->
          <div class="widget latest-posts">
            <header>
              <h3 class="h6">Latest Posts</h3>
            </header>
            <div class="blog-posts">
                {% for post in most_recent %}
                <a href="{% url 'BlogApp:post' %}">
                <div class="item d-flex align-items-center">
                <div class="image"><img src="{{ post.thumbnail.url }}" alt="..." class="img-fluid"></div>
                  <div class="title"><strong>{{ post.title }}</strong>
                    <div class="d-flex align-items-center">
                      <div class="views"><i class="icon-eye"></i>{{ post.view_count }}</div>
                      <div class="comments"><i class="icon-comment"></i>{{ post.comment_count }}</div>
                    </div>
                  </div>
                </div>
              </a>
              {% endfor %}
              <!-- Widget [Categories Widget]-->
          <div class="widget categories">
            <header>
              <h3 class="h6">Categories</h3>
            </header>
             {% for cat in category_count %}
            <div class="item d-flex justify-content-between">
              <a href="#">{{ cat.categories__title }}</a><span>{{ cat.categories__title__count }}</span>
            </div>
            {% endfor %}
          </div>
          <!-- Widget [Tags Cloud Widget]-->
          <div class="widget tags">       
            <header>
              <h3 class="h6">Tags</h3>
            </header>
            <ul class="list-inline">
              <li class="list-inline-item"><a href="#" class="tag">#Business</a></li>
              <li class="list-inline-item"><a href="#" class="tag">#Technology</a></li>
              <li class="list-inline-item"><a href="#" class="tag">#Fashion</a></li>
              <li class="list-inline-item"><a href="#" class="tag">#Sports</a></li>
              <li class="list-inline-item"><a href="#" class="tag">#Economy</a></li>
            </ul>
          </div>
        </aside>
      </div>
    </div>
</html>
    {% endblock content %}

BlogApp/templates/BlogApp/search_result.html
{% extends "BlogApp/base2.html" %}
{% block content %}


<h2> this is the result of the search</h2>
{% for post in queryset %}
<a href="{{ post.get_absolute_url }}">{{ post.title  }}</a>

{% endfor %}
{% endblock %}
 